### ISSUE TITLE
Multiple Select queries

### ISSUE THREAD

**Issue by ghost** [AllieTheDemonHunter/leadtrekker#2]
Good Day Sir

The module is working very well!!! 

If you do have time will you make an small update towards this project that enables the module to send multiple select options into Leadtrekker. It can only send one option at the moment and do get cases where the user can submit multiple options ,

Thank you and keep up the good work!!

**Comment by AllieTheDemonHunter** [comment]
Feature requests:
Preselected select fields: Forms as blocks, which get used in various places, should be able to pickup on which page it is.
Dynamic Source IDs: Depending on a selection in a field, the form should be routed to the Source ID to which correlates. "Form element = Source ID".

**Comment by AllieTheDemonHunter** [comment]
**Key-value pairs MUST be specified as "safe_key|Some readable option".** Use of only alphanumeric characters and underscores is recommended in keys. One option per line.

**Comment by AllieTheDemonHunter** [comment]
@FIXED in `1.2.2`
