### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by AllieTheDemonHunter** [AllieTheDemonHunter/leadtrekker#3]
**Preselected select fields**: Forms as blocks, which get used in various places, should be able to pickup on which page it is.
**Dynamic Source IDs**: Depending on a selection in a field, the form should be routed to the Source ID to which correlates. "Form element = Source ID".

**Comment by AllieTheDemonHunter** [comment]
**Key-value pairs MUST be specified as "safe_key|Some readable option".** Use of only alphanumeric characters and underscores is recommended in keys. One option per line.

**Comment by ghost** [comment]
Thank you kind sir

**Comment by AllieTheDemonHunter** [comment]
Your contributions are appreciated and always welcome.

**Comment by AllieTheDemonHunter** [comment]
I've made several changes to the entire codebase. Currently, the token functionality in `1.2.2` has been resolved.
